import { Article } from './types';

const now = Date.now();
const min = 60 * 1000;
const hr = 60 * min;

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'OpenAI Unveils GPT-5 with Breakthrough Reasoning Capabilities',
    summary: 'The latest model demonstrates unprecedented performance on complex multi-step reasoning tasks.',
    fullContent: 'OpenAI has announced GPT-5, their most advanced language model to date. The model features a new architecture that enables significantly improved reasoning capabilities, particularly in mathematics, coding, and scientific analysis. Early benchmarks show it outperforming human experts in complex multi-step reasoning tasks.',
    source: 'TechCrunch',
    sourceLogo: '⚡',
    category: 'ai',
    imageUrl: 'https://picsum.photos/seed/gpt5/800/450',
    publishedAt: new Date(now - 2 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
  },
  {
    id: '2',
    title: 'Global Markets Rally as Trade Tensions Ease Between Major Economies',
    summary: 'Stock indices surge worldwide after breakthrough diplomatic talks.',
    fullContent: 'Global financial markets experienced a significant rally today following the announcement of new trade agreements between major world economies. The S&P 500 gained 2.3%, while European and Asian markets showed similar gains.',
    source: 'Bloomberg',
    sourceLogo: '📊',
    category: 'trending',
    imageUrl: 'https://picsum.photos/seed/markets/800/450',
    publishedAt: new Date(now - 15 * min).toISOString(),
    url: '#',
    isLive: false,
    isNew: true,
  },
  {
    id: '3',
    title: 'SpaceX Successfully Lands Starship After Orbital Flight Test',
    summary: 'The fully reusable rocket completed a full orbit before executing a precision landing.',
    fullContent: 'SpaceX achieved another historic milestone today as Starship completed its first full orbital flight and successfully landed back at the launch site. The mission lasted approximately 90 minutes.',
    source: 'Ars Technica',
    sourceLogo: '🚀',
    category: 'technology',
    imageUrl: 'https://picsum.photos/seed/spacex/800/450',
    publishedAt: new Date(now - 45 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: false,
  },
  {
    id: '4',
    title: 'Apple Announces Revolutionary Mixed Reality Headset at WWDC',
    summary: 'The new device blends digital content with the real world using advanced spatial computing.',
    fullContent: 'Apple unveiled its next-generation mixed reality headset at the Worldwide Developers Conference, featuring breakthrough display technology and intuitive hand-tracking controls.',
    source: 'The Verge',
    sourceLogo: '🍎',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/apple-mr/800/450',
    publishedAt: new Date(now - 4 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '5',
    title: 'Ceasefire Negotiations Resume After Intense Fighting',
    summary: 'Diplomats from both sides meet for fresh talks as humanitarian corridors are established.',
    fullContent: 'After weeks of intense fighting, representatives from both nations have gathered for renewed ceasefire negotiations. The talks come after international pressure and the establishment of humanitarian corridors.',
    source: 'Al Jazeera',
    sourceLogo: '🕊️',
    category: 'wars',
    imageUrl: 'https://picsum.photos/seed/ceasefire/800/450',
    publishedAt: new Date(now - 30 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
  },
  {
    id: '6',
    title: 'EU Parliament Passes Sweeping AI Regulation Framework',
    summary: 'The new legislation establishes strict guidelines for AI deployment across member states.',
    fullContent: 'The European Union has passed its landmark AI Act, creating the most comprehensive regulatory framework for artificial intelligence in the world. The legislation classifies AI systems by risk level.',
    source: 'Reuters',
    sourceLogo: '🏛️',
    category: 'ai',
    imageUrl: 'https://picsum.photos/seed/eu-ai/800/450',
    publishedAt: new Date(now - 3 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '7',
    title: 'Tesla Unveils Affordable $25,000 Electric Vehicle for Mass Market',
    summary: 'The new compact EV aims to make electric transportation accessible to the average consumer.',
    fullContent: 'Tesla has officially revealed its highly anticipated $25,000 electric vehicle at a special event in Austin, Texas. The compact hatchback features a 300-mile range.',
    source: 'Electrek',
    sourceLogo: '🚗',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/tesla/800/450',
    publishedAt: new Date(now - 16 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '8',
    title: 'Quantum Computer Achieves New Milestone in Error Correction',
    summary: 'IBM\'s latest quantum processor demonstrates fault-tolerant computation at scale.',
    fullContent: 'IBM has announced a major breakthrough in quantum computing with its latest 1,121-qubit processor achieving fault-tolerant quantum computation at scale.',
    source: 'MIT Technology Review',
    sourceLogo: '💻',
    category: 'technology',
    imageUrl: 'https://picsum.photos/seed/quantum/800/450',
    publishedAt: new Date(now - 1 * 24 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '9',
    title: 'Major Cybersecurity Breach Exposes Data of 200 Million Users',
    summary: 'A sophisticated attack on a leading cloud provider has compromised personal information.',
    fullContent: 'A major cybersecurity incident has exposed the personal data of approximately 200 million users across several popular online services.',
    source: 'Wired',
    sourceLogo: '🔒',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/cyber/800/450',
    publishedAt: new Date(now - 6 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '10',
    title: 'UN Peacekeepers Deployed to Stabilize Tensions in Central Africa',
    summary: 'A new multinational force arrives as displaced populations seek safe refuge.',
    fullContent: 'The United Nations has deployed 5,000 peacekeepers to the Central African region following escalating tensions between rival factions.',
    source: 'Reuters',
    sourceLogo: '🏛️',
    category: 'wars',
    imageUrl: 'https://picsum.photos/seed/peacekeepers/800/450',
    publishedAt: new Date(now - 3 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '11',
    title: 'Meta Unveils an A.I. Image Generator That Rivals DALL-E',
    summary: 'The new model can create photorealistic images from text descriptions in seconds.',
    fullContent: 'Meta has released a new AI image generation model that produces photorealistic results competitive with OpenAI\'s DALL-E 3. The model is available through Meta\'s API.',
    source: 'NY Times',
    sourceLogo: '📰',
    category: 'ai',
    imageUrl: 'https://picsum.photos/seed/meta-ai/800/450',
    publishedAt: new Date(now - 5 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '12',
    title: 'Military Analysts Warn of Escalation in South China Sea Dispute',
    summary: 'Naval deployments increase as territorial claims intensify between multiple nations.',
    fullContent: 'Defense analysts are raising concerns about an escalation in the South China Sea, where multiple nations have increased naval deployments.',
    source: 'Defense One',
    sourceLogo: '⚓',
    category: 'wars',
    imageUrl: 'https://picsum.photos/seed/naval/800/450',
    publishedAt: new Date(now - 6 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
];

export const trendingTopics = [
  { topic: '#CeasefireNow', count: '156K posts' },
  { topic: '#GPT5', count: '98K posts' },
  { topic: '#AIRegulation', count: '87K posts' },
  { topic: '#SpaceX', count: '64K posts' },
  { topic: '#TeslaEV', count: '52K posts' },
];

export const topSources = [
  { name: 'NY Times', articles: 342 },
  { name: 'BBC News', articles: 289 },
  { name: 'Al Jazeera', articles: 256 },
  { name: 'The Verge', articles: 231 },
  { name: 'MIT Tech Review', articles: 198 },
];
